apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vulnz-nvd-mirror
      app.kubernetes.io/instance: {{.Release.Name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vulnz-nvd-mirror
        app.kubernetes.io/instance: {{.Release.Name}}
    spec:
      containers:
        - name: vulnz
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-environment-configmap
            {{- if .Values.nvd.secretName }}
            - secretRef:
                name: {{ .Values.nvd.secretName }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
      restartPolicy: Always
status: {}
