# This must be the domain you reach your rundeck with. It is used to configure the grails URL and avoid CSP issues
# @see https://github.com/rundeck/rundeck/issues/4417
externUrl:

image:
  repository: rundeck/rundeck
  # see https://hub.docker.com/r/rundeck/rundeck/tags
  tag:
  pullPolicy: IfNotPresent

executionLogs:
  claim:
    enabled: true
    # required - set this
    storageClass:
    accessMode: ReadWriteOnce
    size: 1G

data:
  claim:
    enabled: true
    # required - set this
    storageClass:
    accessMode: ReadWriteOnce
    size: 1G

addons:
  claim:
    enabled: true
    # required - set this
    storageClass:
    accessMode: ReadWriteOnce
    size: 1G

plugins:
  claim:
    enabled: true
    # required - set this
    storageClass:
    accessMode: ReadWriteOnce
    size: 1G

database:
  # A secret including the following keys `type`,`jdbc`,`port`,`user`,`password`,`database`
  # type can be postgresql/mysql and so forth. Should be in the same namespace as you deploy the helm chart
  secret_name: rundeck-database-secret
  # If set to true, the chart won't consider the secret above for configuration and will default back to rundeck own defaults. Not safe for production.
  # @see https://github.com/EugenMayer/helm-charts/tree/main/charts/rundeck#database
  useInternalH2db: false

securityContext:
  # keep those settings until you really know what you are doing here
  fsGroup: 0
  runAsGroup: 0
  runAsUser: 1000
  fsGroupChangePolicy: "OnRootMismatch"

deployment:
  replicaCount: 1
  annotations: {}
  strategy:
    type: Recreate

ingress:
  enabled: false
  className:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Enable nginx and nginx-service and deployment. If you handle CORS and ssl using your ingress, disable this
# and use the rundeck-backend service as upstream
nginx:
  enabled: true

rundeck:
  # if set, a config-map with this name will be loaded and appended to the
  # /home/rundeck/server/config/rundeck-config.properties file. Use the key 'config'
  # this will later be copied to /tmp/remco-partials/rundeck-config/rundeck-config-custom.properties and then appended
  # to rundecks rundeck-config, see https://docs.rundeck.com/docs/administration/configuration/docker/extending-configuration.html#special-destination-directories
  rundeckConfigConfigMap:
  # if set, a config-map with this name will be loaded and appended to the
  # /home/rundeck/server/config/rundeck-framework.properties file. Use the key 'config'
  # this will later be copied to /tmp/remco-partials/framework/framework-custom.properties and then appended
  # to rundecks framework config, see https://docs.rundeck.com/docs/administration/configuration/docker/extending-configuration.html#special-destination-directories
  rundeckFrameworkConfigMap:
  # Create this secrete in the rundeck namespace.
  # Should have the field `userCredentials` with the value `admin:YOURPASSWORD,user,admin,architect,deploy,build`
  userCredentialsSecretName: user-credentials-secret
  env:
    # @see https://docs.rundeck.com/docs/administration/configuration/docker.html#environment-variables for the options
    RUNDECK_SERVER_FORWARDED: "true"
    RUNDECK_LOGGING_STRATEGY: "CONSOLE"
    # disabling to fix https://github.com/rundeck/rundeck/issues/4417
    # @see https://docs.rundeck.com/docs/administration/configuration/docker.html#security-headers
    RUNDECK_SECURITY_HTTPHEADERS_PROVIDER_CSP_ENABLED: "false"

  # Name of the secret containing SSH files to mount under /home/rundeck/.ssh
  # sshSecrets: "ssh-secret"

  # Name of secret to mount under ~/.kube/
  # kubeConfigSecret: "kube-secret"

  # Name of secret containing additional sensitive Runtime environment variables
  # See https://hub.docker.com/r/rundeck/rundeck/
  # envSecret: "env-secret"

  # Name of secret containing additional files to mount into Rundeck's ~/extra directory.
  # This can be useful for populating a file you reference with RUNDECK_TOKENS_FILE above.
  # extraConfigSecret: "extra-secret"

nameOverride: ""
fullnameOverride: ""

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Replace the nginx.conf file in this chart with a customised config.
nginxConfOverride:
  ""
  # # This example adds configuration for external auth e.g. via oauth2-proxy
  # # It also demonstrates templating in another arbitrary value (authRoles)
  # # to create a map of external users to rundeck roles
  # events {
  #   worker_connections  1024;
  # }
  # http {
  #   map $http_x_forwarded_user $x_forwarded_roles {
  # {{- .Values.authRoles | nindent 4 }}
  #   }
  #   server {
  #     location /metrics/ {
  #       proxy_pass http://localhost:4440;
  #       proxy_set_header Host $http_host;
  #       proxy_set_header X-Forwarded-User metrics;
  #       proxy_set_header X-Forwarded-Roles user;
  #     }
  #     location / {
  #       recursive_error_pages on;
  #       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #       proxy_set_header X-Forwarded-Proto $scheme;
  #       proxy_set_header X-Forwarded-Roles $x_forwarded_roles;
  #       proxy_set_header User-Agent $http_user_agent;
  #       proxy_pass http://localhost:4440;
  #     }
  #   }
  # }

# volumes made available to all containers.
volumes:
  ""
  # - name: plugins
  #   emptyDir: {}

# volumeMounts to add to the rundeck container and configurable paths
volumeMounts: []

# initContainers can be used to download plugins or customize your rundeck installation
# Plugins you on rundeck-plugins are later deployed to /mnt/plugins/libext/ during the bootstrap
initContainers:
  ""
  # - name: download-plugins
  #   image: alpine:3.8
  #   command: [sh, -c]
  #   args:
  #     - wget https://github.com/rundeck-plugins/kubernetes/releases/download/1.0.16/kubernetes-plugin-1.0.16.zip -O /mnt/plugins/libext/kubernetes-plugin-1.0.16.zip
  #   volumeMounts:
  #     - mountPath: /mnt/plugins
  #       name: rundeck-plugins

# sideCars can run additional containers in the pod
sideCars:
  ""
  # - name: cloudsql-proxy
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.17
  #   command:
  #     - "/cloud_sql_proxy"
  #     - "-instances=<instance_end_point>=tcp:3306"
  #   securityContext:
  #     runAsNonRoot: true

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the full name template
  name: ""
