service:
  enabled: true
  # mandatory with enabled service. Will be the ip the LoadBalancer service binds to
  # externalIp:
  # the port to bind on the service, if enabled.
  port: 40000
# set to true for verbose logging
verbose: false
# change this to set the number of replicas
replicas: 1
deployment:
  image:
    # if needed you can use another image
    repository: networkstatic/iperf3
    # adapt if you want to use a different tag
    tag: "latest"
