service:
  enabled: true
  port: 389
  # set this to bind to an external ip. Mandatory if your enable the service
  externalIp:

# set to true for verbose logging
verbose: false
# change this to set the number of replicas
replicas: 1
deployment:
  image:
    # if needed you can use another image
    repository: ghcr.io/eugenmayer/ldaptestserver
    # adapt if you want to use a different tag like type1
    tag: "type2"

