image:
  repository: ghcr.io/eugenmayer/ldaptestserver
  # adapt if you want to use a different tag like type1
  tag: 'type2'
  pullPolicy: Always

service:
  main:
    enabled: true
    #type: ExternalIP
    #externalIP: <exernalIp>
    ports:
      main:
        protocol: tcp
        port: 389
        targetPort: 389

workload:
  main:
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          probes:
            readiness:
              type: tcp
              port: 389
              spec:
                initialDelaySeconds: 10
                periodSeconds: 5
                failureThreshold: 2
            liveness:
              enabled: true
              type: tpc
              port: 389
              spec:
                initialDelaySeconds: 15
                periodSeconds: 5
                failureThreshold: 2

ingress:
  main:
    enabled: false

portal:
  open:
    enabled: false
