image:
  repository: prodrigestivill/postgres-backup-local
  # pick the pg version here: 13, 14 - see https://hub.docker.com/r/prodrigestivill/postgres-backup-local/tags
  # tag: "12"
  pullPolicy: IfNotPresent

persistence:
  storage:
    enabled: true
    size: 1Gi
    mountPath: "/backups"
    type: emptyDir

securityContext:
  container:
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
    readOnlyRootFilesystem: true

service:
  main:
    enabled: false
    ports:
      main:
        protocol: tcp
        port: 8080
        targetPort: 8080

workload:
  main:
    enabled: true
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          env:
            #### MANDATORY
            # those 2 are used by backup.sh directly
            # POSTGRES_HOST:
            # the database(s) to backup (single name or comma seperated list of database)
            # POSTGRES_DB:
            #### OPTIONAL
            POSTGRES_PORT: 5432
            # Setting those 2 for better cli-support https://github.com/prodrigestivill/docker-postgres-backup-local/issues/76
            # PGHOST:
            PGPORT: 5432       
            # PGSSLMODE: "require"    
            # If TRUE, backups all databases and not just the list given in POSTGRES_DB
            POSTGRES_CLUSTER: "FALSE"
            POSTGRES_EXTRA_OPTS: ""
            SCHEDULE: "@daily"
            BACKUP_KEEP_DAYS: 7
            BACKUP_KEEP_WEEKS: 4
            BACKUP_KEEP_MONTHS: 6
            HEALTHCHECK_PORT: "8080"
          envFrom:
            - secretRef:
                name: postgres-backup-local
                # should define following keys
                # those 2 are used by backup.sh directly
                # POSTGRES_USER:
                # POSTGRES_PASSWORD:
                # Setting those 2 for better cli-support https://github.com/prodrigestivill/docker-postgres-backup-local/issues/76
                # PGUSER:
                # PGPASSWORD:

ingress:
  main:
    enabled: false

portal:
  open:
    enabled: false
