apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le
  namespace: {{.Release.Namespace}}
spec:
  acme:
    email: {{required "Please set the dns email!" .Values.le.dns.email}}
    privateKeySecretRef:
      name: le
    server: {{.Values.le.server}}
    solvers:
      # see https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
      - dns01:
          cloudflare:
            email: {{required "Please set the dns email!" .Values.le.dns.email}}
            apiTokenSecretRef:
              name: {{required "Please set the dns secret name!" .Values.le.dns.secret.name}}
              key: {{required "Please set the dns secret key!" .Values.le.dns.secret.key}}
