{{- if and .Values.persistence.config.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config-claim
spec:
{{- with .Values.persistence.config}}
  {{- if .storageClass }}
  storageClassName: {{ required "Please set the storage class for the data volume!" .storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}
