---
apiVersion: v1
kind: Service
metadata:
  name: iobroker
spec:
  selector:
    app.kubernetes.io/name: iobroker
    app.kubernetes.io/instance: {{.Release.Name}}
  ports:
    - port: 8081
      name: web
      targetPort: web
