{{- $fullName := include "postgres-backup-local.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "postgres-backup-local.labels" . | nindent 4 }}
data:
  {{- with .Values.postgres }}
  # those 2 are used by backup.sh directly
  POSTGRES_HOST: {{  required "Please provide the postgres.host!" .host }}
  POSTGRES_PORT:  {{  required "Please provide the postgres.post!" .port | quote }}
  # Setting those 2 Setting those 2 for better cli-support https://github.com/prodrigestivill/docker-postgres-backup-local/issues/76
  PGHOST: {{ required "Please provide the postgres.host!" .host }}
  PGPORT: {{ required "Please provide the postgres.post!" .port | quote }}
  # credentials are stored in a secret
  {{- end }}

  {{- with .Values.backup}}
  # the database(s) to backup (single name or comma seperated list of database)
  POSTGRES_DB: {{ .database.names | quote }}
  # If TRUE, backups all databases and not just the list given in POSTGRES_DB
  POSTGRES_CLUSTER: {{ .database.all | quote }}
  POSTGRES_EXTRA_OPTS: {{ .dumpExtraOpts | quote }}
  SCHEDULE: {{ .schedule | quote }}
  BACKUP_KEEP_DAYS: {{ .retention.keepDays | quote }}
  BACKUP_KEEP_WEEKS: {{ .retention.keepWeeks | quote }}
  BACKUP_KEEP_MONTHS: {{ .retention.keepMonths | quote }}
  {{- end }}

  HEALTHCHECK_PORT: "8080"
{{ toYaml .Values.env | indent 2}}
