{{- if not .Values.postgres.auth.existingSecretName }}
{{- with .Values.postgres.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-backup-local.fullname" . }}
  labels:
  {{- include "postgres-backup-local.labels" . | nindent 4 }}
type: Opaque
stringData:
  # those 2 are used by backup.sh directly
  POSTGRES_USER: {{  required "Please provide a progres.auth.user if you do not provide an existing secret!" .user }}
  POSTGRES_PASSWORD: {{ required "Please provide a progres.auth.password if you do not provide an existing secret!" .password }}
  # Setting those 2 for better cli-support https://github.com/prodrigestivill/docker-postgres-backup-local/issues/76
  PGUSER: {{ required "Please provide a progres.auth.user if you do not provide an existing secret!" .user }}
  PGPASSWORD: {{ required "Please provide a progres.auth.password if you do not provide an existing secret!" .password }}
{{ end }}
{{ end }}
