{{- if not .Values.persistence.existingClaim }}
{{- if .Values.persistence.enabled }}
{{- $fullName := include "postgres-backup-local.fullname" . -}}
{{- with .Values.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ $fullName }}
spec:
  storageClassName: {{ required "Please set the storage class for the plugins volume!" .storageClass | quote }}
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}
{{- end }}
