name: network-tools
description: Debugging Tools / Pods
version: 0.2.3
apiVersion: v2
appVersion: 1.1.0
keywords:
  - network
  - tools
  - development
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/network-tools
home: https://github.com/EugenMayer/helm-charts/tree/main/charts/network-tools
dependencies:
  - name: common
    # https://artifacthub.io/packages/helm/truecharts-library-charts/common
    version: 25.4.2
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
