image:
  repository: debian
  tag: bookworm
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: tcp
        port: 5201
        targetPort: 5201

workload:
  main:
    enabled: true
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          command:
            - "/bin/bash"
          args:
            - "-c"
            - |
              apt update
              apt install -y curl wget iperf3 inetutils-ping telnet dnsutils procps
              echo "run iperf3 on port 5201"
              exec iperf3 -s -p 5201
          probes:
            readiness:
              port: 5201
              type: tcp
              spec:
                initialDelaySeconds: 10
                periodSeconds: 5
                failureThreshold: 2
            liveness:
              enabled: true
              type: tcp
              port: 5201
              spec:
                initialDelaySeconds: 15
                periodSeconds: 5
                failureThreshold: 2
ingress:
  main:
    enabled: false

portal:
  open:
    enabled: false
