apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf3
      app.kubernetes.io/instance: {{.Release.Name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iperf3
        app.kubernetes.io/instance: {{.Release.Name}}
    spec:
      containers:
        - name: iperf3
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          command:
            - iperf3
            - -s
            - -p 40000
            - -i 1
            - --forceflush
            {{- if .Values.verbose }}
            - -V
            {{- end }}
          ports:
            - name: iperf3
              containerPort: 40000
              protocol: TCP
          # Resource limits and requests for the container. By default, no limits are set.
          # Uncomment and modify the lines below if you want to set resource limits and requests using values from values.yaml.
          # resources:
          #   requests:
          #     memory: {{ .Values.resources.requests.memory }}
          #       cpu: {{ .Values.resources.requests.cpu }}
          #   limits:
          #     memory: {{ .Values.resources.limits.memory }}
          #     cpu: {{ .Values.resources.limits.cpu }}
      restartPolicy: Always
status: {}
