{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3
spec:
  type: LoadBalancer
{{- if .Values.service.externalIp -}}
  externalIPs:
    - {{.Values.service.externalIp}}
{{- end }}
  selector:
    app.kubernetes.io/name: iperf3
    app.kubernetes.io/instance: {{.Release.Name}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: 40000
{{- end }}
