{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-test
spec:
  type: LoadBalancer
  externalIPs:
    - {{required "Please set the externalIp if you use the predefined service!" .Values.service.externalIp}}
  selector:
    app.kubernetes.io/name: openldap-test
    app.kubernetes.io/instance: {{.Release.Name}}
  ports:
    - protocol: TCP
      # the port to bind on the externalIp
      port: {{.Values.service.port}}
      targetPort: 389
{{- end }}
