apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-default
  namespace: {{.Release.Namespace}}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  redirectScheme:
    scheme: "https"
    permanent: true
  traefik-real-ip:
    thrustCloudFlare: {{ .Values.cloudflare.enabled }}
    thrustEdgeOn: {{ .Values.edge_one.enabled }}
    thrustLoca: {{ .Values.local.enabled }}
    thrustLocal: {{ .Values.local.enabled }}
    trustedIPs: |-
      {{- range .Values.local.trusted_ips }}
      - {{ . | quote }}
      {{- end }}
