# https://longhorn.io/docs/1.9.0/snapshots-and-backups/scheduling-backups-and-snapshots/#using-the-manifest

apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: {{ .Values.longhorn.backup.schedule_label }}-backup
  namespace: longhorn-system
spec:
  cron: {{ .Values.longhorn.backup.cron }}
  task: "backup-force-create"
  groups:
  {{- with .Values.longhorn.backup.groups }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  retain: {{ .Values.longhorn.backup.retain }}
  concurrency: {{ .Values.longhorn.backup.concurrency }}
  labels:
    schedule: {{ .Values.longhorn.backup.schedule_label }}
