apiVersion: v1
kind: Service
metadata:
  labels:
    kontextwork.de/service: {{ .Chart.Name }}
    kontextwork.de/project: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: {{ .Chart.Name }}
      port: 8080
  selector:
    kontextwork.de/project: {{ .Chart.Name }}
    kontextwork.de/app: {{ .Chart.Name }}
status:
  loadBalancer: {}
