image:
  repository: ghcr.io/eugenmayer/whatsmyip
  # https://github.com/EugenMayer/whatsmyip/pkgs/container/whatsmyip
  tag: 0.0.1
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: true

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

workload:
  main:
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          probes:
            readiness:
              port: 8080
              type: tcp
              spec:
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 2
            liveness:
              enabled: true
              type: tcp
              port: 8080
              spec:
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 2

ingress:
  main:
    enabled: false
    primary: true
    required: false
    ingressClassName: ""
    targetSelector:
      main: main
    hosts:
      - host: whatsmyip.local
        paths:
          - path: /
            pathType: Prefix

portal:
  open:
    enabled: false
