image:
  repository: ghcr.io/jeremylong/open-vulnerability-data-mirror
  pullPolicy: IfNotPresent
  tag: v5.1.2


persistence:
  mirror:
    enabled: true
    size: 1Gi
    mountPath: "/usr/local/apache2/htdocs"

securityContext:
  container:
    # currently supervisord is used and priv. dropped via gosu
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

workload:
  main:
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          env:
            # set this to preseed your API key. the expected structure is
            #NVD_API_KEY:
            #  secretKeyRef:
            #    name: nvd-api-key
            #    key: password
            JAVA_OPT: -Xmx2g
          probes:
            readiness:
              enabled: true
              type: http
              port: 80
              path: /
              spec:
                initialDelaySeconds: 5
                periodSeconds: 5
            liveness:
              enabled: true
              type: http
              port: 80
              path: /
              spec:
                initialDelaySeconds: 30
                periodSeconds: 5

ingress:
  main:
    enabled: false
    primary: true
    required: false
    ingressClassName:  ""
    targetSelector:
      main: main
    hosts:
      -  host: vulnz.local
         paths:
           - path: /
             pathType: Prefix

portal:
  open:
    enabled: false
