deployment:
  replicas: 1

image:
  # FIXME: cannot use the official repo until https://github.com/jeremylong/Open-Vulnerability-Project/pull/114
  # has been merged
  # repository: ghcr.io/jeremylong/vulnz
  repository: ghcr.io/eugenmayer/vulnz
  # tag: "0.0.1"
  pullPolicy: IfNotPresent

# set this to preseed your API key. the expected structure is
# NVD_API_KEY=<key>
nvd:
  secretName:
  # secretName: vulnz-nvd-secret

vulnz:
  env:
    JAVA_OPT: -Xmx2g

ingress:
  enabled: false
  className:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
