image:
  repository: ghcr.io/jeremylong/open-vulnerability-data-mirror
  # see https://github.com/jeremylong/open-vulnerability-cli/pkgs/container/open-vulnerability-data-mirror
  tag: v9.0.4
  pullPolicy: IfNotPresent

persistence:
  mirror:
    enabled: true
    size: 2Gi
    mountPath: "/usr/local/apache2/htdocs"

securityContext:
  container:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
    capabilities:
      add:
        # needed for supervisord to properly kill / handle sigterms
        - KILL
  pod:
    fsGroup: 101

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

workload:
  main:
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          probes:
            readiness:
              port: 80
              type: tcp
              spec:
                initialDelaySeconds: 10
                periodSeconds: 5
                failureThreshold: 2
            liveness:
              enabled: true
              type: tcp
              port: 80
              spec:
                initialDelaySeconds: 15
                periodSeconds: 5
                failureThreshold: 2
          resources:
            limits:
              memory: 3Gi
          env:
            JAVA_OPT: -Xmx3g
            ## go below 2000 (max) since the NVD api fails more often for bigger requests
            MAX_RECORDS_PER_PAGE_ARG: 1000
            ## amount of retries
            MAX_RETRY_ARG: 10
            ## set this to preseed your API key. the expected structure is
            #NVD_API_KEY:
            #  secretKeyRef:
            #    name: nvd-api-key
            #    key: password
            ## show debug logs
            #DEBUG: true

ingress:
  main:
    enabled: false
    primary: true
    required: false
    ingressClassName: ""
    targetSelector:
      main: main
    hosts:
      - host: vulnz.local
        paths:
          - path: /
            pathType: Prefix

portal:
  open:
    enabled: false
