image:
  #repository: ghcr.io/jeremylong/open-vulnerability-data-mirror
  #tag: v7.2.1
  repository: ghcr.io/eugenmayer/vulnz
  # see https://github.com/jeremylong/open-vulnerability-cli/pull/279#issuecomment-2664962058
  tag: v7.3.0-1
  pullPolicy: IfNotPresent

persistence:
  mirror:
    enabled: true
    size: 1Gi
    mountPath: "/usr/local/apache2/htdocs"

securityContext:
  container:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
    capabilities:
      add:
        # needed for supervisord to properly kill / handle sigterms
        - KILL
  pod:
    fsGroup: 101

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

workload:
  main:
    replicas: 1
    strategy: Recreate
    type: Deployment
    podSpec:
      containers:
        main:
          probes:
            readiness:
              port: 80
              type: tcp
              spec:
                initialDelaySeconds: 10
                periodSeconds: 5
                failureThreshold: 2
            liveness:
              enabled: true
              type: tcp
              port: 80
              spec:
                initialDelaySeconds: 15
                periodSeconds: 5
                failureThreshold: 2
          resources:
            limits:
              memory: 2Gi
          env:
            ## fetch max record pre page - cannot be higher then 2000 by API limits
            MAX_RECORDS_PER_PAGE: 2000
            ## set this to preseed your API key. the expected structure is
            #NVD_API_KEY:
            #  secretKeyRef:
            #    name: nvd-api-key
            #    key: password
            ## amount of retries
            #MAX_RETRY: 10
            ## show debug logs
            #DEBUG: true

ingress:
  main:
    enabled: false
    primary: true
    required: false
    ingressClassName: ""
    targetSelector:
      main: main
    hosts:
      - host: vulnz.local
        paths:
          - path: /
            pathType: Prefix

portal:
  open:
    enabled: false
