{{- $fullName := include "rundeck.fullname" . -}}
{{- $labels := include "rundeck.labels" . -}}

{{- if and .Values.executionLogs.claim.enabled }}
{{- with .Values.executionLogs.claim}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-execution-logs
  labels: {{ $labels | indent 4 }}
  annotations:
 
spec:
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}