{{- if and .Values.nginx.enabled }}
{{- $fullName := include "rundeck.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-nginx
  labels: {{ include "rundeck.labels" . | indent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: 1
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullName }}-nginx
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        # This will restart the nginx pod if the nginx configuration changed
        app.kubernetes.io/name: {{ $fullName }}-nginx
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
      serviceAccountName: {{ include "rundeck.serviceAccountName" . }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-configmap
            items:
              - key: nginx.conf
                path: nginx.conf
{{ end }}
