{{- if and .Values.nginx.enabled }}
{{- $fullName := include "rundeck.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: rundeck-nginx
  labels: {{ include "rundeck.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $fullName }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
