{{- $fullName := include "rundeck.fullname" . -}}
{{- $labels := include "rundeck.labels" . -}}

{{- if and .Values.plugins.claim.enabled }}
{{- with .Values.plugins.claim}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-plugins-claim
  labels: {{ $labels | indent 4 }}
spec:
  {{- if .storageClass }}
  storageClassName: {{ required "Please set the storage class for the plugins volume!" .storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}