apiVersion: v1
kind: Service
metadata:
  name: { { include "rundeck.fullname" . } }
  labels: { { include "rundeck.labels" . | indent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: { { include "rundeck.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
