{{- if .Values.pods.rick.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-rick
  namespace: {{ .Release.Namespace }}
  labels:
    kontextwork.de/app: debian
    kontextwork.de/project: network-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      pickle: rick
      kontextwork.de/app: debian
      kontextwork.de/project: network-tools
  template:
    metadata:
      labels:
        pickle: rick
        kontextwork.de/app: debian
        kontextwork.de/project: network-tools
    spec:
      containers:
        - name: debian-rick
          image: debian:bullseye
          command: ["/bin/bash"]
          args: ["/custom-scripts/bootstrap.sh"]
          volumeMounts:
            - name: boostrap-wrapper-script
              mountPath: /custom-scripts
          {{- if and .Values.persistence.enabled }}
            - mountPath: /mnt
              name: tmp
          {{ end }}
          ports:
            - name: iperf3
              containerPort: 5201
              protocol: TCP
      {{- if and .Values.strictPodPlacement.enabled }}
      nodeName: {{ .Values.strictPodPlacement.rickAgent }}
      {{ else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: pickle
                      operator: In
                      values:
                        - morty
                topologyKey: beta.kubernetes.io/instance-type
      {{ end }}
      volumes:
        {{- if and .Values.persistence.enabled }}
        - name: tmp
          persistentVolumeClaim:
            claimName: network-tools-storage-tmp
        {{ end }}
        - name: boostrap-wrapper-script
          configMap:
            name: boostrap-wrapper-script
{{- end }}
